Add missing quote_ident
Otherwise migrating to a schema that needs quoting leads to syntax error:

```
ERROR:  Action: Views  Diagnostics: line=PL/pgSQL function clone_schema(text,text,boolean,boolean) line 335 at EXECUTE. 42601. syntax error at or near "-"
```