Added support for aggre
This fixes the following issue:
Action: Functions  Diagnostics: line=SQL statement "SELECT pg_get_functiondef(func_oid)"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 537 at SQL statement. 42809. "concat" is an aggregate function
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean) line 851 at RAISE
somedb=> SELECT pg_get_functiondef(func_oid);
ERROR:  column "func_oid" does not exist
LINE 1: SELECT pg_get_functiondef(func_oid);
                                  ^

Current implementation does not separate regular function and aggregate functions. However "pg_get_functiondef()" does not work with aggregate functions. Therefore some code has been added to support that.