Fixes issue on GRANTs when dealing with agg. func.
When working with aggregate functions, information_schema.routines contains NULL as routine_type value. Therefore, the query
    SELECT 'GRANT ' || rp.privilege_type || ' ON ' || r.routine_type || ' ' || quote_ident(dest_schema) || '.' || rp.routine_name || ' (' || pg_get_function_identity_arguments(p.oid) || ') TO ' || string_agg(distinct rp.grantee, ',') || ';' as func_dcl
    FROM information_schema.routine_privileges rp, information_schema.routines r, pg_proc p, pg_namespace n 
    where rp.routine_schema = quote_ident(source_schema) and rp.is_grantable = 'YES' and rp.routine_schema = r.routine_schema and rp.routine_name = r.routine_name and rp.routine_schema = n.nspname and n.oid = p.pronamespace and p.proname = r.routine_name 

returns NULL (result of a concatenation with text and NULL) and give the error:
ERROR:  Action: PRIVS: Functions/Procedures  Diagnostics: line=PL/pgSQL function public.clone_schema(text,text,boolean,boolean) line 837 at EXECUTE. 22004. query string argument of EXECUTE is null

Using COALESCE(r.routine_type, 'FUNCTION') solves the problem.